<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:ns0="RestConversionService_convertCelsiusToFahrenheit_request"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:tns="saibot.airport/services/utility/conversion" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ns0 tns oraxsl DVMFunctions BasicCredentialsUserFunction UUIDUserFunction IsUserInRoleFunction IsUserInGroupFunction XrefFunctions"
                xmlns:nxsd="http://xmlns.oracle.com/pcbpel/nxsd" xmlns:common="saibot.airport/data/common"
                xmlns:ns9="http://xmlns.oracle.com/ConversionServices/TemperatureConversionService/RestConversionService">
    <oracle-xsl-mapper:schema>
        <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
        <oracle-xsl-mapper:mapSources>
            <oracle-xsl-mapper:source type="XSD">
                <oracle-xsl-mapper:schema location="../Schemas/NXSD/nxsd_getTemperatureURL.xsd"/>
                <oracle-xsl-mapper:rootElement name="URIParams"
                                               namespace="RestConversionService_convertCelsiusToFahrenheit_request"/>
            </oracle-xsl-mapper:source>
        </oracle-xsl-mapper:mapSources>
        <oracle-xsl-mapper:mapTargets>
            <oracle-xsl-mapper:target type="XSD">
                <oracle-xsl-mapper:schema location="../Schemas/ConversionService.xsd"/>
                <oracle-xsl-mapper:rootElement name="temperatureCelsiusToFahrenheitRequestMessage"
                                               namespace="saibot.airport/services/utility/conversion"/>
            </oracle-xsl-mapper:target>
        </oracle-xsl-mapper:mapTargets>
        <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [SAT AUG 02 07:12:22 CEST 2014].-->
    </oracle-xsl-mapper:schema>
    <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
    <xsl:template match="/">
        <tns:temperatureCelsiusToFahrenheitRequestMessage>
            <tns:temperature>
            <!-- Author's Note: apparently the XML created by the REST adapter from the URI parameters does not conform to the NXSD definition created by the tooling in JDeveloper.
                 The child element celsiusTemperature is created in a different namespace than specified as target namespace for the NXSD schema:
                 "http://xmlns.oracle.com/ConversionServices/TemperatureConversionService/RestConversionService" 
                 instead of
                 RestConversionService_convertCelsiusToFahrenheit_request                 
                 
                 that is the reason below the ns9:  namespace prefix appears before the celsiusTemperature element and the visual mapper indicates a question mark
              -->   

                <xsl:value-of select="/ns0:URIParams/ns9:celsiusTemperature"/>
            </tns:temperature>
        </tns:temperatureCelsiusToFahrenheitRequestMessage>
    </xsl:template>
</xsl:stylesheet>
