<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ns0="saibot.airport/services/utility/conversion"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:tns="saibot.airport/services/utility/conversion/celsiusTemperatureConversionRESTJSONResponse"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                xmlns:ns9="http://xmlns.oracle.com/ConversionServices/TemperatureConversionService/RestConversionService"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ns0 tns oraxsl DVMFunctions BasicCredentialsUserFunction UUIDUserFunction IsUserInRoleFunction IsUserInGroupFunction XrefFunctions"
                xmlns:common="saibot.airport/data/common" xmlns:nxsd="http://xmlns.oracle.com/pcbpel/nxsd">
    <oracle-xsl-mapper:schema>
        <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
        <oracle-xsl-mapper:mapSources>
            <oracle-xsl-mapper:source type="XSD">
                <oracle-xsl-mapper:schema location="../Schemas/ConversionService.xsd"/>
                <oracle-xsl-mapper:rootElement name="temperatureCelsiusToFahrenheitResponseMessage"
                                               namespace="saibot.airport/services/utility/conversion"/>
            </oracle-xsl-mapper:source>
        </oracle-xsl-mapper:mapSources>
        <oracle-xsl-mapper:mapTargets>
            <oracle-xsl-mapper:target type="XSD">
                <oracle-xsl-mapper:schema location="../Schemas/NXSD/nxsd_getTemperatureResponseJSON.xsd"/>
                <oracle-xsl-mapper:rootElement name="TemperatureConversionResult"
                                               namespace="saibot.airport/services/utility/conversion/celsiusTemperatureConversionRESTJSONResponse"/>
            </oracle-xsl-mapper:target>
        </oracle-xsl-mapper:mapTargets>
        <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [SAT AUG 02 07:14:20 CEST 2014].-->
    </oracle-xsl-mapper:schema>
    <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
    <xsl:template match="/">
        <tns:TemperatureConversionResult>
            <tns:temperatureConversion>
            <!-- Author's Note: apparently the XML expected by the REST adapter from the response to be converted to JSON does not conform to the NXSD definition created by the tooling in JDeveloper.
                 The child element fahrenheitTemperature is expected in a different namespace than specified as target namespace for the NXSD schema:
                 "http://xmlns.oracle.com/ConversionServices/TemperatureConversionService/RestConversionService" 
                 instead of
                 RestConversionService_convertCelsiusToFahrenheit_request                 
                 
                 that is the reason why below the ns9:  namespace prefix appears before the fahrenheitTemperature element and the visual mapper indicates a question mark
              -->
                <ns9:fahrenheitTemperature>
                    <xsl:value-of select="/ns0:temperatureCelsiusToFahrenheitResponseMessage/ns0:temperature"/>
                </ns9:fahrenheitTemperature>
            </tns:temperatureConversion>
        </tns:TemperatureConversionResult>
    </xsl:template>
</xsl:stylesheet>
