<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="InternalSecurityScreeningEvaluation_DecisionService"
     targetNamespace="http://xmlns.oracle.com/InternalSecurityScreeningEvaluation/InternalSecurityScreeningEvaluation_DecisionService"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="http://xmlns.oracle.com/InternalSecurityScreeningEvaluation/InternalSecurityScreeningEvaluation_DecisionService"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="InternalSecurityScreeningEvaluation.InternalSecurityScreeningEvaluation_DecisionService">
        <plnk:role name="IDecisionService" portType="tns:IDecisionService"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://xmlns.oracle.com/InternalSecurityScreeningEvaluation/InternalSecurityScreeningEvaluation_DecisionService"
         location="InternalSecurityScreeningEvaluation_DecisionService.wsdl"/>
</wsdl:definitions>
