<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/coherence/FlightStatusCacheService_step1/FlightStatusCacheService/RemoveFromCache" name="RemoveFromCache-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="RemoveFromCache.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/coherence/FlightStatusCacheService_step1/FlightStatusCacheService/RemoveFromCache"/>
    <wsdl:binding name="Remove_ptt-binding" type="rem:Remove_ptt" xmlns:rem="http://xmlns.oracle.com/pcbpel/adapter/coherence/FlightStatusCacheService_step1/FlightStatusCacheService/RemoveFromCache">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="Remove">
            <soap:operation soapAction="Remove"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>