<wsdl:definitions name="FlightScheduleService" targetNamespace="saibot.airport/services/private/flightschedule" xmlns:pfs="saibot.airport/services/private/flightschedule" xmlns:tns="saibot.airport/services/private/flightschedule" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
    
    <wsdl:types>
   <xsd:schema elementFormDefault="qualified">
      <xsd:import namespace="saibot.airport/services/private/flightschedule" schemaLocation="../Schemas/PrivateSubmitFlightScheduleService.xsd"/>
    </xsd:schema>
  </wsdl:types>
  
    <wsdl:message name="requestMessage">
        <wsdl:part name="in" element="pfs:submitScheduledFlightRequestMessage"/>
    </wsdl:message>
    <wsdl:message name="replyMessage">
        <wsdl:part name="out" element="pfs:submitScheduledFlightResponseMessage"/>
    </wsdl:message>
    <wsdl:portType name="FlightScheduleServicePortType">
        <wsdl:operation name="submitFlightSchedule">
            <wsdl:input message="tns:requestMessage"/>
            <wsdl:output message="tns:replyMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="execute_bind" type="tns:FlightScheduleServicePortType">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="submitFlightSchedule">
            <soap:operation style="document" soapAction="submitFlightSchedule"/>
            <wsdl:input>
                <soap:body use="literal" namespace="saibot.airport/services/private/flightschedule"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" namespace="saibot.airport/services/private/flightschedule"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>