<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="FlightService"
     targetNamespace="saibot.airport/services/flight"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="saibot.airport/services/flight"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="FlightStatusProcess">
        <plnk:role name="FlightServicePortType" portType="tns:FlightServicePortType"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="saibot.airport/services/flight" location="FlightService.wsdl"/>
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="saibot.airport/services/flight" schemaLocation="../Schemas/FlightService.xsd"/>
        </xsd:schema>
    </wsdl:types>
</wsdl:definitions>
