<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="AircraftServiceNegotiation"
     targetNamespace="saibot.airport/operational/aircraftservice"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:acs="saibot.airport/operational/aircraftservice"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="AircraftServiceNegotiationProcessor">
        <plnk:role name="AircraftServiceNegotiation" portType="acs:AircraftServiceNegotiation"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="saibot.airport/operational/aircraftservice" location="AircraftServiceNegotiation.wsdl"/>
</wsdl:definitions>
