<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="AirportAccreditationService"
     targetNamespace="saibot.airport/security"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="saibot.airport/security"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="AirportAccreditationService">
        <plnk:role name="AirportAccreditationServiceCallback" portType="tns:AirportAccreditationServiceCallback"/>
        <plnk:role name="AirportAccreditationService" portType="tns:AirportAccreditationService"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="saibot.airport/security" location="AirportAccreditationService.wsdl"/>
</wsdl:definitions>
