<wsdl:definitions name="ParallelFlightEnrichmentService" targetNamespace="saibot.airport/services/flightschedule" xmlns:fse="saibot.airport/services/flightschedule" xmlns:tns="saibot.airport/services/flightschedule" xmlns:inp1="saibot.airport/services/flightschedule" xmlns:inp2="saibot.airport/services/flightschedule" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
    
    <wsdl:types>
   <xsd:schema elementFormDefault="qualified">
      <xsd:import namespace="saibot.airport/services/flightschedule" schemaLocation="../Schemas/FlightScheduleService.xsd"/>
    </xsd:schema>
  </wsdl:types>
  
    <wsdl:message name="requestMessage">
        <wsdl:part name="in" element="fse:enrichScheduledFlightRequestMessage"/>
    </wsdl:message>
    <wsdl:message name="replyMessage">
        <wsdl:part name="out" element="fse:enrichScheduledFlightResponseMessage"/>
    </wsdl:message>
    <wsdl:portType name="ParallelFlightEnrichmentServicePortType">
        <wsdl:operation name="enrichFlightSchedule">
            <wsdl:input message="tns:requestMessage"/>
            <wsdl:output message="tns:replyMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="execute_bind" type="tns:ParallelFlightEnrichmentServicePortType">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="enrichFlightSchedule">
            <soap:operation style="document" soapAction="enrichFlightSchedule"/>
            <wsdl:input>
                <soap:body use="literal" namespace="saibot.airport/services/flightschedule"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" namespace="saibot.airport/services/flightschedule"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>