<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:ns0="saibot.airport/security/ldap"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:tns="http://platform.integration.oracle/blocks/adapter/fw/metadata/AddUser"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns0 tns oraxsl xp20 xref mhdr oraext dvm socket"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/ldap/AirportAccreditationService-step2/AirportAccreditationService/AddUser"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/LDAPService.wsdl"/>
        <oracle-xsl-mapper:rootElement name="AddUserRequest" namespace="saibot.airport/security/ldap"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/AddUser.wsdl"/>
        <oracle-xsl-mapper:rootElement name="addRequest"
                                       namespace="http://platform.integration.oracle/blocks/adapter/fw/metadata/AddUser"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [MON OCT 27 05:25:10 CET 2014].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:addRequest>
      <dn>
        <xsl:value-of select="concat ('uid=', /ns0:AddUserRequest/ns0:UserId, ',ou=ExternalStaff,o=saibot.airport ' )"/>
      </dn>
      <requestAttributes>
        <cn>
          <value>
            <xsl:value-of select="/ns0:AddUserRequest/ns0:UserId"/>
          </value>
        </cn>
        <sn>
          <value>
            <xsl:value-of select="/ns0:AddUserRequest/ns0:UserId"/>
          </value>
        </sn>
        <destinationIndicator>
          <value>
            <xsl:value-of select="/ns0:AddUserRequest/ns0:SaibotAirportSecurity"/>
          </value>
        </destinationIndicator>
        <employeeNumber>
          <value>
            <xsl:value-of select="/ns0:AddUserRequest/ns0:EmployeeNumber"/>
          </value>
        </employeeNumber>
        <givenName>
          <value>
            <xsl:value-of select="/ns0:AddUserRequest/ns0:GivenName"/>
          </value>
        </givenName>
        <mail>
          <value>
            <xsl:value-of select="/ns0:AddUserRequest/ns0:EmailAddress"/>
          </value>
        </mail>
        <manager>
          <value>
            <xsl:if test="/ns0:AddUserRequest/ns0:ManagerId != ''">
              <xsl:value-of select="concat ('uid=', /ns0:AddUserRequest/ns0:ManagerId, ',ou=ExternalStaff,o=saibot.airport ' )"/>
            </xsl:if>
          </value>
        </manager>
        <mobile>
          <value>
            <xsl:value-of select="/ns0:AddUserRequest/ns0:MobileTelephone"/>
          </value>
        </mobile>
        <ou>
          <value>
            <xsl:value-of select="concat('organizationalUnitName=',/ns0:AddUserRequest/ns0:OrganizationId,',ou=BusinessPartners,o=saibot.airport')"/>
          </value>
        </ou>
        <title>
          <value>
            <xsl:value-of select="/ns0:AddUserRequest/ns0:FunctionTitle"/>
          </value>
        </title>
        <uid>
          <value>
            <xsl:value-of select="/ns0:AddUserRequest/ns0:UserId"/>
          </value>
        </uid>
        <userPassword>
          <value>
            <xsl:value-of select="/ns0:AddUserRequest/ns0:TemporaryPassword"/>
          </value>
        </userPassword>
      </requestAttributes>
    </tns:addRequest>
  </xsl:template>
</xsl:stylesheet>
