<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://finance.airport.saibot/"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns0="saibot.airport/services/aircraftmovement"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ns0 tns xp20 oraxsl mhdr oraext dvm xref socket"
                xmlns:ns1="saibot.airport/data/reference" xmlns:ns2="saibot.airport/data/common"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:ns3="http://finance.airport.saibot/types">
    <oracle-xsl-mapper:schema>
        <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
        <oracle-xsl-mapper:mapSources>
            <oracle-xsl-mapper:source type="WSDL">
                <oracle-xsl-mapper:schema location="../WSDLs/AircraftMovementService.wsdl"/>
                <oracle-xsl-mapper:rootElement name="reportAircraftMovementRequestMessage"
                                               namespace="saibot.airport/services/aircraftmovement"/>
            </oracle-xsl-mapper:source>
        </oracle-xsl-mapper:mapSources>
        <oracle-xsl-mapper:mapTargets>
            <oracle-xsl-mapper:target type="WSDL">
                <oracle-xsl-mapper:schema location="../WSDLs/FinanceAircraftMovementReporter.wsdl"/>
                <oracle-xsl-mapper:rootElement name="reportAircraftMovement"
                                               namespace="http://finance.airport.saibot/"/>
            </oracle-xsl-mapper:target>
        </oracle-xsl-mapper:mapTargets>
        <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [WED AUG 06 14:34:12 CEST 2014].-->
    </oracle-xsl-mapper:schema>
    <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
    <xsl:template match="/">
        <tns:reportAircraftMovement>
            <arg0>
                <aircraftIataEquipmentCode>
                    <xsl:value-of select="/ns0:reportAircraftMovementRequestMessage/ns0:AircraftModel"/>
                </aircraftIataEquipmentCode>
                <airportIataCode>
                    <xsl:value-of select="/ns0:reportAircraftMovementRequestMessage/ns0:ConnectingAirport"/>
                </airportIataCode>
                <arrivalOrDeparture>
                    <xsl:value-of select="/ns0:reportAircraftMovementRequestMessage/ns0:ArrivalOrDeparture"/>
                </arrivalOrDeparture>
                <carrierIataCode>
                    <xsl:value-of select="/ns0:reportAircraftMovementRequestMessage/ns0:Carrier"/>
                </carrierIataCode>
                <flightnumber>
                    <xsl:value-of select="/ns0:reportAircraftMovementRequestMessage/ns0:FlightNumber"/>
                </flightnumber>
                <movementTimestamp>
                    <xsl:value-of select="/ns0:reportAircraftMovementRequestMessage/ns0:ActionDateAndTime"/>
                </movementTimestamp>
                <numberOfPassengers>
                    <xsl:value-of select="/ns0:reportAircraftMovementRequestMessage/ns0:NumberOfPassengers"/>
                </numberOfPassengers>
            </arg0>
        </tns:reportAircraftMovement>
    </xsl:template>
</xsl:stylesheet>
