<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:ns0="http://aircraftmovement.operations.airport.saibot/"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:tns="saibot.airport/services/aircraftmovement"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns0 tns oraxsl xp20 xref mhdr oraext dvm socket"
                xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:ns1="saibot.airport/data/reference"
                xmlns:ns2="saibot.airport/data/common">
    <oracle-xsl-mapper:schema>
        <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
        <oracle-xsl-mapper:mapSources>
            <oracle-xsl-mapper:source type="WSDL">
                <oracle-xsl-mapper:schema location="../WSDLs/AircraftMovementReporter.wsdl"/>
                <oracle-xsl-mapper:rootElement name="reportAircraftActivity"
                                               namespace="http://aircraftmovement.operations.airport.saibot/"/>
            </oracle-xsl-mapper:source>
        </oracle-xsl-mapper:mapSources>
        <oracle-xsl-mapper:mapTargets>
            <oracle-xsl-mapper:target type="WSDL">
                <oracle-xsl-mapper:schema location="../WSDLs/AircraftMovementService.wsdl"/>
                <oracle-xsl-mapper:rootElement name="reportAircraftMovementRequestMessage"
                                               namespace="saibot.airport/services/aircraftmovement"/>
            </oracle-xsl-mapper:target>
        </oracle-xsl-mapper:mapTargets>
        <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [WED AUG 06 16:03:17 CEST 2014].-->
    </oracle-xsl-mapper:schema>
    <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
    <xsl:template match="/">
        <tns:reportAircraftMovementRequestMessage>
            <tns:ActionDateAndTime>
                <xsl:value-of select="/ns0:reportAircraftActivity/arg0"/>
            </tns:ActionDateAndTime>
            <tns:FlightNumber>
                <xsl:value-of select="/ns0:reportAircraftActivity/arg1"/>
            </tns:FlightNumber>
            <tns:Carrier>
                <xsl:value-of select="/ns0:reportAircraftActivity/arg2"/>
            </tns:Carrier>
            <tns:ArrivalOrDeparture>
                <xsl:value-of select="/ns0:reportAircraftActivity/arg4"/>
            </tns:ArrivalOrDeparture>
            <tns:ConnectingAirport>
                <xsl:value-of select="/ns0:reportAircraftActivity/arg3"/>
            </tns:ConnectingAirport>
            <tns:AircraftModel>
                <xsl:value-of select="/ns0:reportAircraftActivity/arg5"/>
            </tns:AircraftModel>
            <tns:NumberOfPassengers>
                <xsl:value-of select="/ns0:reportAircraftActivity/arg6"/>
            </tns:NumberOfPassengers>
        </tns:reportAircraftMovementRequestMessage>
    </xsl:template>
</xsl:stylesheet>
