<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:tns="http://xmlns.oracle.com/xdb/SAIBOT_FINANCE" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:ns0="saibot.airport/services/aircraftmovement"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns0 tns oraxsl DVMFunctions BasicCredentialsUserFunction UUIDUserFunction IsUserInRoleFunction IsUserInGroupFunction XrefFunctions"
                xmlns:reference="saibot.airport/data/reference" xmlns:common="saibot.airport/data/common">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../Schemas/AircraftMovementService.xsd"/>
        <oracle-xsl-mapper:rootElement name="reportAircraftMovementRequestMessage"
                                       namespace="saibot.airport/services/aircraftmovement"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../Resources/SAIBOT_FINANCE_AIRCRAFT_MOVEMENT_REPORT_T.xsd"/>
        <oracle-xsl-mapper:rootElement name="AIRCRAFT_MOVEMENT_REPORT_T"
                                       namespace="http://xmlns.oracle.com/xdb/SAIBOT_FINANCE"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [WED AUG 06 13:18:54 CEST 2014].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:AIRCRAFT_MOVEMENT_REPORT_T>
      <MOVEMENT_TIMESTAMP>
        <xsl:value-of select="/ns0:reportAircraftMovementRequestMessage/ns0:ActionDateAndTime"/>
      </MOVEMENT_TIMESTAMP>
      <FLIGHTNUMBER>
        <xsl:value-of select="/ns0:reportAircraftMovementRequestMessage/ns0:FlightNumber"/>
      </FLIGHTNUMBER>
      <CARRIER_IATA_CODE>
        <xsl:value-of select="/ns0:reportAircraftMovementRequestMessage/ns0:Carrier"/>
      </CARRIER_IATA_CODE>
      <AIRPORT_IATA_CODE>
        <xsl:value-of select="/ns0:reportAircraftMovementRequestMessage/ns0:ConnectingAirport"/>
      </AIRPORT_IATA_CODE>
      <ARRIVAL_OR_DEPARTURE>
        <xsl:value-of select="/ns0:reportAircraftMovementRequestMessage/ns0:ArrivalOrDeparture"/>
      </ARRIVAL_OR_DEPARTURE>
      <AIRCRAFT_IATA_EQUIPMENT_CODE>
        <xsl:value-of select="/ns0:reportAircraftMovementRequestMessage/ns0:AircraftModel"/>
      </AIRCRAFT_IATA_EQUIPMENT_CODE>
      <NUMBER_OF_PASSENGERS>
        <xsl:value-of select="/ns0:reportAircraftMovementRequestMessage/ns0:NumberOfPassengers"/>
      </NUMBER_OF_PASSENGERS>
    </tns:AIRCRAFT_MOVEMENT_REPORT_T>
  </xsl:template>
</xsl:stylesheet>
