<wsdl:definitions
     name="CoherenceCacheRetriever"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/coherence/FlightService/QuickAndSlowHello/CoherenceCacheRetriever"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/coherence/FlightService/QuickAndSlowHello/CoherenceCacheRetriever"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:imp2="saibot.airport/utility/cache"
     xmlns:imp1="http://xmlns.oracle.com/pcbpel/adapter/coherence/CoherenceCacheRetriever/request"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="Get_plt" >
    <plt:role name="Get_role" >
      <plt:portType name="tns:Get_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="saibot.airport/utility/cache" schemaLocation="../Schemas/Cache.xsd" />
      </schema>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/coherence/CoherenceCacheRetriever/request" schemaLocation="../Schemas/CoherenceCacheRetrieverRequest.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="Get_msg">
        <wsdl:part name="body" element="imp1:GetRequest"/>
    </wsdl:message>
    <wsdl:message name="GetResponse_msg">
        <wsdl:part name="body" element="imp2:cacheResult"/>
    </wsdl:message>
    <wsdl:portType name="Get_ptt">
        <wsdl:operation name="Get">
            <wsdl:input message="tns:Get_msg"/>
            <wsdl:output message="tns:GetResponse_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
