<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/top/CreateCountryDB"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                xmlns:ns0="saibot.airport/services/utility/reference"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns0 tns oraxsl DVMFunctions BasicCredentialsUserFunction UUIDUserFunction IsUserInRoleFunction IsUserInGroupFunction XrefFunctions"
                xmlns:refData="saibot.airport/data/reference" xmlns:common="saibot.airport/data/common">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../Schemas/CountryService.xsd"/>
        <oracle-xsl-mapper:rootElement name="createCountryRequestMessage"
                                       namespace="saibot.airport/services/utility/reference"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../Resources/CreateCountryDB_table.xsd"/>
        <oracle-xsl-mapper:rootElement name="CmnCountriesCollection"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/CreateCountryDB"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.2.0.0(XSLT Build 130601.2155.4487) AT [SUN DEC 29 16:37:53 CET 2013].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:CmnCountriesCollection>
      <tns:CmnCountries>
        <tns:id/>
        <xsl:if test="/ns0:createCountryRequestMessage/ns0:NewCountry/refData:code">
          <tns:code>
            <xsl:value-of select="/ns0:createCountryRequestMessage/ns0:NewCountry/refData:code"/>
          </tns:code>
        </xsl:if>
        <xsl:if test="/ns0:createCountryRequestMessage/ns0:NewCountry/refData:name">
          <tns:name>
            <xsl:value-of select="/ns0:createCountryRequestMessage/ns0:NewCountry/refData:name"/>
          </tns:name>
        </xsl:if>
        <xsl:if test="/ns0:createCountryRequestMessage/ns0:NewCountry/refData:tailcode">
          <tns:tailcode>
            <xsl:value-of select="/ns0:createCountryRequestMessage/ns0:NewCountry/refData:tailcode"/>
          </tns:tailcode>
        </xsl:if>
        <xsl:if test="/ns0:createCountryRequestMessage/ns0:NewCountry/refData:Flag">
          <tns:flag>
            <xsl:value-of select="/ns0:createCountryRequestMessage/ns0:NewCountry/refData:Flag"/>
          </tns:flag>
        </xsl:if>
      </tns:CmnCountries>
    </tns:CmnCountriesCollection>
  </xsl:template>
</xsl:stylesheet>
