<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tns="saibot.airport/services/flightreport"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ns0="saibot.airport/data/flight/FlightEventLogFileWriter"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ns0 tns oraxsl DVMFunctions BasicCredentialsUserFunction UUIDUserFunction IsUserInRoleFunction IsUserInGroupFunction XrefFunctions"
                xmlns:nxsd="http://xmlns.oracle.com/pcbpel/nxsd" xmlns:reference="saibot.airport/data/reference"
                xmlns:common="saibot.airport/data/common" xmlns:flight="saibot.airport/data/flight">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../Resources/nxsd_FlightEventLogFile.xsd"/>
        <oracle-xsl-mapper:rootElement name="FlightEventLog"
                                       namespace="saibot.airport/data/flight/FlightEventLogFileWriter"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../Schemas/FlightReportService.xsd"/>
        <oracle-xsl-mapper:rootElement name="getFlightReportResponseMessage"
                                       namespace="saibot.airport/services/flightreport"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [SAT AUG 02 22:55:13 CEST 2014].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:getFlightReportResponseMessage>
      <tns:FlightLog>
<xsl:for-each select="/ns0:FlightEventLog/ns0:FlightEventLogEntry">
        <tns:FlightLogEntry>
            <tns:EventTimestamp>
              <xsl:value-of select="ns0:StatusTimestamp"/>
            </tns:EventTimestamp>
            <tns:Carrier>
              <xsl:value-of select="ns0:Aircarrier"/>
            </tns:Carrier>
            <tns:FlightNumber>
              <xsl:value-of select="ns0:FlightNumber"/>
            </tns:FlightNumber>
            <tns:FlightDate>
              <xsl:value-of select="ns0:FlightDate"/>
            </tns:FlightDate>
            <tns:FlightStatus>
              <flight:Status>
                <xsl:value-of select="ns0:NewStatus"/>
              </flight:Status>
              <flight:Action>
                <xsl:value-of select="ns0:Action"/>
              </flight:Action>
              <flight:CheckinCounter>
                <xsl:value-of select="ns0:CheckinCounter"/>
              </flight:CheckinCounter>
              <flight:Runway>
                <xsl:value-of select="ns0:Runway"/>
              </flight:Runway>
              <flight:GateLocation>
                <reference:Terminal>
                  <xsl:value-of select="ns0:Terminal"/>
                </reference:Terminal>
                <reference:Pier>
                  <xsl:value-of select="ns0:Pier"/>
                </reference:Pier>
                <reference:Gate>
                  <xsl:value-of select="ns0:Gate"/>
                </reference:Gate>
              </flight:GateLocation>
            </tns:FlightStatus>
          </tns:FlightLogEntry>
</xsl:for-each>
      </tns:FlightLog>
    </tns:getFlightReportResponseMessage>
  </xsl:template>
</xsl:stylesheet>
