<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                xmlns:ns0="saibot.airport/services/flightreport"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:tns="saibot.airport/data/flight/FlightEventLogFileWriter"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ns0 tns oraxsl DVMFunctions BasicCredentialsUserFunction UUIDUserFunction IsUserInRoleFunction IsUserInGroupFunction XrefFunctions"
                xmlns:reference="saibot.airport/data/reference" xmlns:common="saibot.airport/data/common"
                xmlns:flight="saibot.airport/data/flight" xmlns:nxsd="http://xmlns.oracle.com/pcbpel/nxsd">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../Schemas/FlightReportService.xsd"/>
        <oracle-xsl-mapper:rootElement name="reportFlightStatusUpdateRequestMessage"
                                       namespace="saibot.airport/services/flightreport"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../Resources/nxsd_FlightEventLogFile.xsd"/>
        <oracle-xsl-mapper:rootElement name="FlightEventLog"
                                       namespace="saibot.airport/data/flight/FlightEventLogFileWriter"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [SAT AUG 02 16:02:42 CEST 2014].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:FlightEventLog>
      <tns:FlightEventLogEntry>
        <tns:FlightDate>
          <xsl:value-of select="/ns0:reportFlightStatusUpdateRequestMessage/ns0:flightStatusEvent/ns0:FlightDate"/>
        </tns:FlightDate>
        <tns:Aircarrier>
          <xsl:value-of select="/ns0:reportFlightStatusUpdateRequestMessage/ns0:flightStatusEvent/ns0:Carrier"/>
        </tns:Aircarrier>
        <tns:FlightNumber>
          <xsl:value-of select="/ns0:reportFlightStatusUpdateRequestMessage/ns0:flightStatusEvent/ns0:FlightNumber"/>
        </tns:FlightNumber>
        <tns:StatusTimestamp>
          <xsl:value-of select="/ns0:reportFlightStatusUpdateRequestMessage/ns0:flightStatusEvent/ns0:FlightStatus/flight:Status"/>
        </tns:StatusTimestamp>
        <tns:NewStatus>
          <xsl:value-of select="/ns0:reportFlightStatusUpdateRequestMessage/ns0:flightStatusEvent/ns0:FlightStatus/flight:Status"/>
        </tns:NewStatus>
        <tns:Action>
          <xsl:value-of select="/ns0:reportFlightStatusUpdateRequestMessage/ns0:flightStatusEvent/ns0:FlightStatus/flight:Action"/>
        </tns:Action>
        <tns:Terminal>
          <xsl:value-of select="/ns0:reportFlightStatusUpdateRequestMessage/ns0:flightStatusEvent/ns0:FlightStatus/flight:GateLocation/reference:Terminal"/>
        </tns:Terminal>
        <tns:Pier>
          <xsl:value-of select="/ns0:reportFlightStatusUpdateRequestMessage/ns0:flightStatusEvent/ns0:FlightStatus/flight:GateLocation/reference:Pier"/>
        </tns:Pier>
        <tns:Gate>
          <xsl:value-of select="/ns0:reportFlightStatusUpdateRequestMessage/ns0:flightStatusEvent/ns0:FlightStatus/flight:GateLocation/reference:Gate"/>
        </tns:Gate>
        <tns:Runway>
          <xsl:value-of select="/ns0:reportFlightStatusUpdateRequestMessage/ns0:flightStatusEvent/ns0:FlightStatus/flight:Runway"/>
        </tns:Runway>
        <tns:CheckinCounter>
          <xsl:value-of select="/ns0:reportFlightStatusUpdateRequestMessage/ns0:flightStatusEvent/ns0:FlightStatus/flight:CheckinCounter"/>
        </tns:CheckinCounter>
      </tns:FlightEventLogEntry>
    </tns:FlightEventLog>
  </xsl:template>
</xsl:stylesheet>
