<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="AirportService"
     targetNamespace="http://xmlns.oracle.com/AirportServicesPlatform/AirportServiceRequest/AirportService"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="http://xmlns.oracle.com/AirportServicesPlatform/AirportServiceRequest/AirportService"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="AircraftServiceRequestProcessor">
        <plnk:role name="AircraftServiceCallback" portType="tns:AircraftServiceCallback"/>
        <plnk:role name="AircraftService" portType="tns:AircraftService"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://xmlns.oracle.com/AirportServicesPlatform/AirportServiceRequest/AirportService"
         location="AircraftService.wsdl"/>
</wsdl:definitions>
