<wsdl:definitions
     name="QueryAirportsDB"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ReferenceDataServices/AirportService/QueryAirportsDB"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ReferenceDataServices/AirportService/QueryAirportsDB"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/QueryAirportsDB"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="QueryAirportsDB_plt" >
    <plt:role name="QueryAirportsDB_role" >
      <plt:portType name="tns:QueryAirportsDB_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/QueryAirportsDB" schemaLocation="QueryAirportsDB_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="QueryAirportsDBSelect_inputParameters">
        <wsdl:part name="QueryAirportsDBSelect_inputParameters" element="top:QueryAirportsDBSelect_pIATACode_pCountryCode_pAirportNameInputParameters"/>
    </wsdl:message>
    <wsdl:message name="CmnAirportsCollection_msg">
        <wsdl:part name="CmnAirportsCollection" element="top:CmnAirportsCollection"/>
    </wsdl:message>
    <wsdl:portType name="QueryAirportsDB_ptt">
        <wsdl:operation name="QueryAirportsDBSelect">
            <wsdl:input message="tns:QueryAirportsDBSelect_inputParameters"/>
            <wsdl:output message="tns:CmnAirportsCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
