<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:ns0="saibot.airport/security"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:tns="saibot.airport/security/nxsd/SuspiciousTransactionsLog"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns0 tns oraxsl xp20 xref mhdr oraext dvm socket"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/file/SaibotAirportSecurity/SaibotAirportSecurity/SuspiciousTransactionsLog">
    <oracle-xsl-mapper:schema>
        <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
        <oracle-xsl-mapper:mapSources>
            <oracle-xsl-mapper:source type="XSD">
                <oracle-xsl-mapper:schema location="../Schemas/SecurityEvents.xsd"/>
                <oracle-xsl-mapper:rootElement name="SuspectCreditCardEvent" namespace="saibot.airport/security"/>
            </oracle-xsl-mapper:source>
        </oracle-xsl-mapper:mapSources>
        <oracle-xsl-mapper:mapTargets>
            <oracle-xsl-mapper:target type="WSDL">
                <oracle-xsl-mapper:schema location="../WSDLs/SuspiciousTransactionsLog.wsdl"/>
                <oracle-xsl-mapper:rootElement name="Log"
                                               namespace="saibot.airport/security/nxsd/SuspiciousTransactionsLog"/>
            </oracle-xsl-mapper:target>
        </oracle-xsl-mapper:mapTargets>
        <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [SUN SEP 14 13:32:29 CEST 2014].-->
    </oracle-xsl-mapper:schema>
    <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
    <xsl:template match="/">
        <tns:Log>
            <tns:LogEntry>
                <tns:creditCardNumber>
                    <xsl:value-of select="/ns0:SuspectCreditCardEvent/ns0:CreditCardNumber"/>
                </tns:creditCardNumber>
                <tns:timestamp>
                    <xsl:value-of select="xp20:current-dateTime ( )"/>
                </tns:timestamp>
                <tns:numberOfPurchases>
                    <xsl:value-of select="count (/ns0:SuspectCreditCardEvent/ns0:Purchases )"/>
                </tns:numberOfPurchases>
                <tns:totalAmount>
                    <xsl:value-of select="/ns0:SuspectCreditCardEvent/ns0:SumAmounts"/>
                </tns:totalAmount>
            </tns:LogEntry>
        </tns:Log>
    </xsl:template>
</xsl:stylesheet>
