<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ReferenceDataServices/AirportService/QueryAirportsDB" name="QueryAirportsDB-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="../Resources/QueryAirportsDB.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ReferenceDataServices/AirportService/QueryAirportsDB"/>
    <wsdl:binding name="QueryAirportsDB_ptt-binding" type="quer:QueryAirportsDB_ptt" xmlns:quer="http://xmlns.oracle.com/pcbpel/adapter/db/ReferenceDataServices/AirportService/QueryAirportsDB">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="QueryAirportsDBSelect">
            <soap:operation soapAction="QueryAirportsDBSelect"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>