<xsl:stylesheet version="1.0"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ns0 tns oraxsl DVMFunctions BasicCredentialsUserFunction UUIDUserFunction IsUserInRoleFunction IsUserInGroupFunction XrefFunctions"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:tns="myspace.com/reference"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns0="http://TargetNamespace.com/fileReference"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                xmlns:nxsd="http://xmlns.oracle.com/pcbpel/nxsd">
    <oracle-xsl-mapper:schema>
        <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
        <oracle-xsl-mapper:mapSources>
            <oracle-xsl-mapper:source type="XSD">
                <oracle-xsl-mapper:schema location="../Resources/nxsd_schema1.xsd"/>
                <oracle-xsl-mapper:rootElement name="domains" namespace="http://TargetNamespace.com/fileReference"/>
            </oracle-xsl-mapper:source>
            <oracle-xsl-mapper:source type="XSD">
                <oracle-xsl-mapper:schema location="../Schemas/CodeLists.xsd"/>
                <oracle-xsl-mapper:rootElement name="CodeListIdentification" namespace="myspace.com/reference"/>
                <oracle-xsl-mapper:param name="domainName"/>
            </oracle-xsl-mapper:source>
        </oracle-xsl-mapper:mapSources>
        <oracle-xsl-mapper:mapTargets>
            <oracle-xsl-mapper:target type="XSD">
                <oracle-xsl-mapper:schema location="../Schemas/CodeLists.xsd"/>
                <oracle-xsl-mapper:rootElement name="RawCodeListValues" namespace="myspace.com/reference"/>
            </oracle-xsl-mapper:target>
        </oracle-xsl-mapper:mapTargets>
        <!--GENERATED BY ORACLE XSL MAPPER 12.1.2.0.0(XSLT Build 130601.2155.4487) AT [SUN JAN 26 18:41:01 CET 2014].-->
    </oracle-xsl-mapper:schema>
    <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
    <xsl:param name="domainName"/>
    <!--    <xsl:param name="domainName"/> -->
    <xsl:template match="/">
        <tns:RawCodeListValues>
            <tns:ValuesInJSON>
                <!-- //ns0:domains/ns0:domain[ns0:domainName=$domainName]/ns0:domainValues -->
                <xsl:value-of select="//ns0:domains/ns0:domain[ns0:domainName=$domainName]/ns0:domainValues"/>
            </tns:ValuesInJSON>
        </tns:RawCodeListValues>
    </xsl:template>
</xsl:stylesheet>
